In [3]:
import numpy as np

In [27]:
array1=np.array([[23,25,30],[34,78,67],[56,18,34]])
array1

array([[23, 25, 30],
       [34, 78, 67],
       [56, 18, 34]])

In [6]:
array2=np.array([[26,89,45],[56,76,64],[34,98,48]])
array2

array([[26, 89, 45],
       [56, 76, 64],
       [34, 98, 48]])

1.1-Addition

In [8]:
array3=array1 + array2
print("\nUsing Operator:\n",array3)
array3=np.add(array1,array2)
print("\nUsing NumPy Function:\n",array3)


Using Operator:
 [[ 49 114  75]
 [ 90 154 131]
 [ 90 116  82]]

Using NumPy Function:
 [[ 49 114  75]
 [ 90 154 131]
 [ 90 116  82]]


1.2-Subtraction

In [9]:
array3=array1 - array2
print("\nUsing Operator:\n",array3)
array3=np.subtract(array1,array2)
print("\nUsing NumPy Function:\n",array3)



Using Operator:
 [[ -3 -64 -15]
 [-22   2   3]
 [ 22 -80 -14]]

Using NumPy Function:
 [[ -3 -64 -15]
 [-22   2   3]
 [ 22 -80 -14]]


1.3-Multiplication

In [10]:
array3=array1 * array2
print("\nUsing Operator:\n",array3)
array3=np.multiply(array1,array2)
print("\nUsing NumPy Function:\n",array3)


Using Operator:
 [[ 598 2225 1350]
 [1904 5928 4288]
 [1904 1764 1632]]

Using NumPy Function:
 [[ 598 2225 1350]
 [1904 5928 4288]
 [1904 1764 1632]]


1.4-Division

In [11]:
array3=array1 / array2
print("\nUsing Operator:\n",array3)
array3=np.divide(array1,array2)
print("\nUsing NumPy Function:\n",array3)


Using Operator:
 [[0.88461538 0.28089888 0.66666667]
 [0.60714286 1.02631579 1.046875  ]
 [1.64705882 0.18367347 0.70833333]]

Using NumPy Function:
 [[0.88461538 0.28089888 0.66666667]
 [0.60714286 1.02631579 1.046875  ]
 [1.64705882 0.18367347 0.70833333]]


1.5-Mod

In [14]:
array3=array1 % array2
print("\nUsing Operator:\n",array3)
array3=np.mod(array1,array2)
print("\nUsing NumPy Function:\n",array3)


Using Operator:
 [[23 25 30]
 [34  2  3]
 [22 18 34]]

Using NumPy Function:
 [[23 25 30]
 [34  2  3]
 [22 18 34]]


1.6-Dot Product

In [15]:
array3=np.dot(array1,array2)
print(array3)

[[ 3018  6887  4075]
 [ 7530 15520  9738]
 [ 3620  9684  5304]]


1.7-Transpose

In [21]:
array3=np.transpose(array1)
print(array3)
print("\n")
array3=array1.transpose()
print(array3)

[[23 34 56]
 [25 78 18]
 [30 67 34]]


[[23 34 56]
 [25 78 18]
 [30 67 34]]


2.1-Horizontal Stacking

In [29]:
array3=np.hstack((array1,array2))
array3

array([[23, 25, 30, 26, 89, 45],
       [34, 78, 67, 56, 76, 64],
       [56, 18, 34, 34, 98, 48]])

2.2-Vertical Stacking

In [30]:
array3=np.vstack((array1,array2))
array3

array([[23, 25, 30],
       [34, 78, 67],
       [56, 18, 34],
       [26, 89, 45],
       [56, 76, 64],
       [34, 98, 48]])

2.3-Stacking

In [31]:
array3=np.stack((array1,array2),axis=0)
array3

array([[[23, 25, 30],
        [34, 78, 67],
        [56, 18, 34]],

       [[26, 89, 45],
        [56, 76, 64],
        [34, 98, 48]]])

In [32]:
array3=np.stack((array1,array2),axis=1)
array3

array([[[23, 25, 30],
        [26, 89, 45]],

       [[34, 78, 67],
        [56, 76, 64]],

       [[56, 18, 34],
        [34, 98, 48]]])

In [34]:
array3=np.stack((array1,array2),axis=2)
array3

array([[[23, 26],
        [25, 89],
        [30, 45]],

       [[34, 56],
        [78, 76],
        [67, 64]],

       [[56, 34],
        [18, 98],
        [34, 48]]])

1-D Stacking

In [41]:
arr1=np.array([1,5,7])
arr2=np.array([4,9,8])
arr3=np.stack((arr1,arr2),axis=0)
print(arr3)
print("\n")
arr3=np.stack((arr1,arr2),axis=1)
print(arr3)

[[1 5 7]
 [4 9 8]]


[[1 4]
 [5 9]
 [7 8]]


In [44]:
print(array1.shape)
print(arr1.shape)

(3, 3)
(3,)


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr4=arr.reshape(2,3,2)
print(arr4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
